### ISSUE TITLE
App Crashes without Internet Connection

### ISSUE THREAD

**Issue by AleksanderSleszynski** [meeDamian/Basic-Info#36]
```
01-01 23:33:56.016 26546-26546/com.meedamian.info E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.meedamian.info, PID: 26546
java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.gson.JsonElement com.google.gson.JsonObject.get(java.lang.String)' on a null object reference
    at com.meedamian.info.RemoteData$1.onCompleted(RemoteData.java:36)
    at com.meedamian.info.RemoteData$1.onCompleted(RemoteData.java:33)
    at com.koushikdutta.async.future.SimpleFuture.handleCallbackUnlocked(SimpleFuture.java:107)
    at com.koushikdutta.async.future.SimpleFuture.setComplete(SimpleFuture.java:141)
    at com.koushikdutta.async.future.SimpleFuture.setComplete(SimpleFuture.java:124)
    at com.koushikdutta.ion.IonRequestBuilder$1.run(IonRequestBuilder.java:244)
    at com.koushikdutta.async.AsyncServer$RunnableWrapper.run(AsyncServer.java:57)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5254)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by meeDamian** [comment]
StackTrace?

**Comment by AleksanderSleszynski** [comment]
@chester1000 Done.
